'use server';

import { revalidatePath } from 'next/cache';

import { authenticateAndCheckBan } from '@/lib/auth';
import { consumeMaiaGamePoint } from '@/lib/points';
import { RATE_LIMITS, checkRateLimit } from '@/lib/security/rate-limit';

type StartMaiaGameResult =
  | { ok: true; charged: boolean }
  | {
      ok: false;
      error: 'signInRequired' | 'banned' | 'rateLimited' | 'insufficient_balance' | 'invalid';
    };

/**
 * Charge for one Maia game at game-start (per-game billing — model B).
 *
 * Called by the `/games/new/*` forms before navigating into the play
 * route, only when the selected engine is Maia. Every viewer pays one
 * coin per game — there is no subscription exemption.
 *
 * @param clientGameId  A UUID generated by the client per game-start
 *   attempt. Anchors the ledger row's idempotency key so a retried call
 *   (lost response, double click) never double-charges. There is no
 *   server-side game record to key off — Maia games are not persisted.
 *
 * Soft enforcement by design: Maia inference runs client-side against an
 * immutable-cached, openly-licensed model, so a tampered client can skip
 * this call. The honest path charges; valuable server-side artefacts are
 * gated separately on the `maia_game` ledger row.
 */
export async function startMaiaGame(clientGameId: string): Promise<StartMaiaGameResult> {
  if (typeof clientGameId !== 'string' || clientGameId.length === 0 || clientGameId.length > 100) {
    return { ok: false, error: 'invalid' };
  }

  const auth = await authenticateAndCheckBan();
  if ('error' in auth) {
    return { ok: false, error: auth.error === 'banned' ? 'banned' : 'signInRequired' };
  }

  const rateLimitResult = await checkRateLimit(auth.user.id, RATE_LIMITS.startMaiaGame);
  if ('error' in rateLimitResult) {
    return { ok: false, error: 'rateLimited' };
  }

  const result = await consumeMaiaGamePoint(auth.user.id, clientGameId);
  if (!result.ok) {
    return { ok: false, error: 'insufficient_balance' };
  }

  // Balance moved — refresh the points page so the user sees it on return.
  revalidatePath('/mypage/coins');

  return { ok: true, charged: !result.alreadyCharged };
}
