'use server';

import type { ActionResult } from '@/lib/action-types';
import { authenticateAndCheckBan } from '@/lib/auth';
import { consumeMaiaGamePoint } from '@/lib/points';
import { RATE_LIMITS, checkRateLimit } from '@/lib/security/rate-limit';
import { isMaiaFreeForUser } from '@/lib/users/can-use-maia';
import { UUID_RE } from '@/lib/validations/uuid';

/**
 * How a Maia game start was settled:
 *
 * - `free`           — the player is at or above `MAIA_FREE_LEVEL`; nothing
 *                      was charged and there is no ledger row to link the
 *                      game to.
 * - `charged`        — one coin was debited for this `clientGameId`.
 * - `alreadyCharged` — a retry of a `clientGameId` that had already been
 *                      debited (lost response, double click); nothing new
 *                      was charged.
 */
export type MaiaGameStartBilling = 'free' | 'charged' | 'alreadyCharged';

type StartMaiaGameResult = ActionResult<
  { billing: MaiaGameStartBilling },
  | 'signInRequired'
  | 'banned'
  | 'rateLimited'
  | 'insufficient_balance'
  | 'chargeRequired'
  | 'invalid'
>;

type StartMaiaGameOptions = {
  /**
   * Whether the player has acknowledged the per-game coin charge. The form
   * only shows the confirmation dialog when its server-resolved access
   * state says the game is payable, so a free-tier player never sees it;
   * if the server then finds the player is NOT free (the page is stale —
   * the level is read at render time), charging silently would spend a
   * coin the player was never asked about. `false` makes that case return
   * `chargeRequired` instead, and the form opens the confirmation.
   */
  allowCharge: boolean;
};

/**
 * Settle the billing for one Maia game at game-start, then let the form
 * navigate into the play route.
 *
 * Called by the `/games/new/*` forms before navigating, only when the
 * selected engine is Maia. Players at or above `MAIA_FREE_LEVEL` are not
 * charged — Maia is free for them. Everyone else pays one coin per game;
 * there is no subscription exemption. The level is re-read here rather
 * than trusted from the page, so the billing decision is the server's.
 *
 * The free path still runs through this action (rather than the form
 * skipping it) so the rate limit applies to every Maia start and so the
 * server, not the page, decides who pays.
 *
 * @param clientGameId  A UUID generated by the client (`crypto.randomUUID()`)
 *   per game-start attempt. Anchors the ledger row's idempotency key so a
 *   retried call (lost response, double click) never double-charges. There is
 *   no server-side game record to key off — Maia games are not persisted. The
 *   value is pinned to canonical UUID form to keep the ledger key space tight;
 *   cross-user replay is already closed by the `userId`-namespaced key in
 *   `consumeMaiaGamePoint`.
 *
 * Soft enforcement by design: Maia inference runs client-side against an
 * immutable-cached, openly-licensed model, so a tampered client can skip
 * this call. The honest path charges; valuable server-side artefacts are
 * gated separately on the `maia_game` ledger row and on the level.
 */

export async function startMaiaGame(
  clientGameId: string,
  options: StartMaiaGameOptions
): Promise<StartMaiaGameResult> {
  if (typeof clientGameId !== 'string' || !UUID_RE.test(clientGameId)) {
    return { error: 'invalid' };
  }

  const auth = await authenticateAndCheckBan();
  if ('error' in auth) {
    return { error: auth.error === 'banned' ? 'banned' : 'signInRequired' };
  }

  const rateLimitResult = await checkRateLimit(auth.user.id, RATE_LIMITS.startMaiaGame);
  if ('error' in rateLimitResult) {
    return { error: 'rateLimited' };
  }

  if (await isMaiaFreeForUser(auth.user.id)) {
    return { success: true, billing: 'free' };
  }

  if (!options.allowCharge) {
    return { error: 'chargeRequired' };
  }

  const result = await consumeMaiaGamePoint(auth.user.id, clientGameId);
  if (!result.ok) {
    return { error: 'insufficient_balance' };
  }

  // Balance moved — refresh the points page so the user sees it on return.
  // No revalidatePath: /mypage/coins is a dynamic route, so it re-queries the
  // balance whenever the player next opens it. Revalidating here would instead
  // force a server re-render of the page the player is leaving, right as the
  // game launches.

  return { success: true, billing: result.alreadyCharged ? 'alreadyCharged' : 'charged' };
}
