/**
 * Shared-game persistence.
 *
 * @description
 * Writes a published game (and, for account-less authors, its manage token) in
 * one transaction. The game `id` is a UUIDv7 generated by the schema's
 * `$defaultFn`; `status` defaults to `'public'`. Reads / mutations beyond
 * publish live in their own modules as the feature grows.
 *
 * @see {@link @/lib/games/publish-game} for the validation + column derivation
 *      that produces the inputs here.
 */
import { cache } from 'react';

import { and, eq, inArray, isNull } from 'drizzle-orm';
import 'server-only';

import { generateManageToken } from '@/lib/games/manage-token';
import type { GameColumns, ValidatedGame } from '@/lib/games/publish-game';

import { db } from './index';
import type { GameRecord } from './schema';
import { gameTokens, games, profiles } from './schema';

/** Statuses a published game is publicly viewable in. */
const VISIBLE_STATUSES = ['public', 'unlisted'] as const;

export type SharedGameDetail = {
  game: GameRecord;
  /** Author's display name, or null for account-less / deleted authors. */
  authorName: string | null;
};

/**
 * Fetch a publicly-visible shared game by id with its author's display name.
 * Returns null when the id does not exist or the game is hidden / removed /
 * soft-deleted (the privileged `db` connection bypasses RLS, so visibility is
 * filtered here). Admin / owner views of non-public games are a separate path.
 */
export const getGameById = cache(async (id: string): Promise<SharedGameDetail | null> => {
  const [row] = await db
    .select({ game: games, authorName: profiles.displayName })
    .from(games)
    .leftJoin(profiles, eq(profiles.id, games.authorId))
    .where(
      and(eq(games.id, id), isNull(games.deletedAt), inArray(games.status, [...VISIBLE_STATUSES]))
    )
    .limit(1);

  return row ? { game: row.game, authorName: row.authorName } : null;
});

export type PublishGameResult = {
  id: string;
  /** Raw manage token, returned ONLY for account-less authors to store client-side. */
  manageToken?: string;
};

/**
 * Insert a published game. When `authorId` is null (account-less author), a
 * manage token is minted and its hash stored in `game_tokens`; the raw token is
 * returned so the caller can hand it to the client. Registered authors own the
 * row via `author_id` and get no token.
 */
export async function publishGame(params: {
  authorId: string | null;
  game: ValidatedGame;
  columns: GameColumns;
}): Promise<PublishGameResult> {
  const { authorId, game, columns } = params;

  return db.transaction(async (tx) => {
    const [row] = await tx
      .insert(games)
      .values({
        authorId,
        title: game.title,
        description: game.description,
        moves: game.moves,
        startingFen: game.startingFen,
        playerColor: game.playerColor,
        engineConfig: game.engineConfig,
        operationLogs: game.operationLogs,
        result: game.result,
        engineKind: columns.engineKind,
        engineElo: columns.engineElo,
        moveCount: columns.moveCount,
        cleanRate: columns.cleanRate,
      })
      .returning({ id: games.id });

    let manageToken: string | undefined;
    if (!authorId) {
      const { token, tokenHash } = generateManageToken();
      await tx.insert(gameTokens).values({ gameId: row.id, tokenHash });
      manageToken = token;
    }

    return { id: row.id, manageToken };
  });
}
