/**
 * Shared-game writes.
 *
 * @description
 * Writes a published game (and, for account-less authors, its manage token) in
 * one transaction, plus the owner mutations (soft delete, field edits). Reads
 * live in `./games-read`, mutation authorization in `./games-auth`. The game
 * `id` is a UUIDv7 generated by the schema's `$defaultFn`; `status` defaults
 * to `'public'`.
 *
 * @see {@link @/lib/games/publish-game} for the validation + column derivation
 *      that produces the inputs here.
 */
import { eq } from 'drizzle-orm';
import 'server-only';

import { generateManageToken } from '@/lib/games/manage-token';
import type { GameColumns, ValidatedGame } from '@/lib/games/publish-game';

import { db } from './index';
import { feedItems, gameTokens, games } from './schema';

export type PublishGameResult = {
  id: string;
  /** Raw manage token, returned ONLY for account-less authors to store client-side. */
  manageToken?: string;
};

/**
 * Insert a published game. When `authorId` is null (account-less author), a
 * manage token is minted and its hash stored in `game_tokens`; the raw token is
 * returned so the caller can hand it to the client. Registered authors own the
 * row via `author_id` and get no token.
 */
export async function publishGame(params: {
  authorId: string | null;
  game: ValidatedGame;
  columns: GameColumns;
}): Promise<PublishGameResult> {
  const { authorId, game, columns } = params;

  return db.transaction(async (tx) => {
    const [row] = await tx
      .insert(games)
      .values({
        authorId,
        title: game.title,
        description: game.description,
        moves: game.moves,
        startingFen: game.startingFen,
        playerColor: game.playerColor,
        engineConfig: game.engineConfig,
        operationLogs: game.operationLogs,
        playSettings: game.playSettings,
        playSettingsLog: game.playSettingsLog,
        result: game.result,
        engineKind: columns.engineKind,
        engineElo: columns.engineElo,
        moveCount: columns.moveCount,
        cleanRate: columns.cleanRate,
      })
      .returning({ id: games.id });

    let manageToken: string | undefined;
    if (!authorId) {
      const { token, tokenHash } = generateManageToken();
      await tx.insert(gameTokens).values({ gameId: row.id, tokenHash });
      manageToken = token;
    } else {
      // Surface the publish on the home timeline. Account-less games have no
      // actor (feed_items.actor_id is NOT NULL), so they list under
      // /games/shared but never emit a feed item.
      await tx.insert(feedItems).values({
        entityType: 'game',
        entityId: row.id,
        actorId: authorId,
        metadata: { result: game.result },
      });
    }

    return { id: row.id, manageToken };
  });
}

/**
 * Soft-delete a shared game (owner or moderation). Stamps `deleted_at` only —
 * `status` (the visibility tier) is intentionally left untouched so the two
 * lifecycle axes stay orthogonal. RLS / reads filter on `deleted_at IS NULL`.
 */
export async function softDeleteSharedGame(gameId: string): Promise<void> {
  await db.update(games).set({ deletedAt: new Date() }).where(eq(games.id, gameId));
}

/** Update an owner-editable field set (title / description). */
export async function updateSharedGameFields(
  gameId: string,
  fields: { title: string; description: string | null }
): Promise<void> {
  await db
    .update(games)
    .set({ title: fields.title, description: fields.description })
    .where(eq(games.id, gameId));
}
