/**
 * Shared-game persistence.
 *
 * @description
 * Writes a published game (and, for account-less authors, its manage token) in
 * one transaction. The game `id` is a UUIDv7 generated by the schema's
 * `$defaultFn`; `status` defaults to `'public'`. Reads / mutations beyond
 * publish live in their own modules as the feature grows.
 *
 * @see {@link @/lib/games/publish-game} for the validation + column derivation
 *      that produces the inputs here.
 */
import { cache } from 'react';

import { and, desc, eq, inArray, isNull, sql } from 'drizzle-orm';
import 'server-only';

import { generateManageToken, manageTokenMatches } from '@/lib/games/manage-token';
import type { GameColumns, ValidatedGame } from '@/lib/games/publish-game';

import { db } from './index';
import type { GameRecord } from './schema';
import { feedItems, gameTokens, games, profiles } from './schema';

/** Statuses a published game is publicly viewable in. */
const VISIBLE_STATUSES = ['public', 'unlisted'] as const;

/** Public author profile for attribution (avatar + name + profile link). */
export type SharedGameAuthor = {
  username: string;
  displayName: string | null;
  avatarUrl: string | null;
};

export type SharedGameDetail = {
  game: GameRecord;
  /** Author profile, or null for account-less / hard-deleted authors. */
  author: SharedGameAuthor | null;
};

/**
 * Fetch a publicly-visible shared game by id with its author's public profile
 * (for avatar + name + profile-link attribution). Returns null when the id
 * does not exist or the game is hidden / removed / soft-deleted (the privileged
 * `db` connection bypasses RLS, so visibility is filtered here). Admin / owner
 * views of non-public games are a separate path.
 */
export const getGameById = cache(async (id: string): Promise<SharedGameDetail | null> => {
  const [row] = await db
    .select({
      game: games,
      authorUsername: profiles.username,
      authorDisplayName: profiles.displayName,
      authorAvatarUrl: profiles.avatarUrl,
    })
    .from(games)
    .leftJoin(profiles, eq(profiles.id, games.authorId))
    .where(
      and(eq(games.id, id), isNull(games.deletedAt), inArray(games.status, [...VISIBLE_STATUSES]))
    )
    .limit(1);

  if (!row) return null;

  // username is NOT NULL on profiles, so its presence means the join matched a
  // real author; null means an account-less (anonymous) game.
  const author: SharedGameAuthor | null = row.authorUsername
    ? {
        username: row.authorUsername,
        displayName: row.authorDisplayName,
        avatarUrl: row.authorAvatarUrl,
      }
    : null;

  return { game: row.game, author };
});

/** Compact projection for gallery cards (no JSONB move/log payloads). */
export type SharedGameListItem = {
  id: string;
  title: string;
  /** Body excerpt for the card; null when the author left it blank. */
  description: string | null;
  /** Opening position rendered as the card thumbnail; null = standard start. */
  startingFen: string | null;
  createdAt: Date;
  engineKind: 'stockfish' | 'maia';
  engineElo: number;
  result: 'win' | 'loss' | 'draw';
  moveCount: number;
  cleanRate: number | null;
  /** Author profile for the card avatar; null for an account-less author. */
  author: {
    username: string;
    displayName: string | null;
    avatarUrl: string | null;
  } | null;
};

/** Gallery sort modes (kept in sync with the page's sort control). */
export type SharedGamesSort = 'new' | 'clean' | 'strong';

/**
 * Publicly-listed games for the gallery. Only `public` games appear here —
 * `unlisted` games are reachable by direct link ({@link getGameById}) but
 * excluded from the catalog. Sort:
 * - 'new' (default): newest first via the time-ordered UUIDv7 id.
 * - 'clean': highest blindfold clean-rate first (nulls last).
 * - 'strong': strongest opponent first (unified Elo).
 * Every mode tie-breaks on id desc so paging stays stable.
 */
export async function listSharedGames(
  sort: SharedGamesSort = 'new',
  limit = 30
): Promise<SharedGameListItem[]> {
  const orderBy =
    sort === 'clean'
      ? [sql`${games.cleanRate} DESC NULLS LAST`, desc(games.id)]
      : sort === 'strong'
        ? [desc(games.engineElo), desc(games.id)]
        : [desc(games.id)];

  const rows = await db
    .select({
      id: games.id,
      title: games.title,
      description: games.description,
      startingFen: games.startingFen,
      createdAt: games.createdAt,
      engineKind: games.engineKind,
      engineElo: games.engineElo,
      result: games.result,
      moveCount: games.moveCount,
      cleanRate: games.cleanRate,
      authorUsername: profiles.username,
      authorDisplayName: profiles.displayName,
      authorAvatarUrl: profiles.avatarUrl,
    })
    .from(games)
    .leftJoin(profiles, eq(profiles.id, games.authorId))
    .where(and(isNull(games.deletedAt), eq(games.status, 'public')))
    .orderBy(...orderBy)
    .limit(limit);

  return rows.map((r) => ({
    id: r.id,
    title: r.title,
    description: r.description,
    startingFen: r.startingFen,
    createdAt: r.createdAt,
    engineKind: r.engineKind,
    engineElo: r.engineElo,
    result: r.result,
    moveCount: r.moveCount,
    cleanRate: r.cleanRate,
    author: r.authorUsername
      ? {
          username: r.authorUsername,
          displayName: r.authorDisplayName,
          avatarUrl: r.authorAvatarUrl,
        }
      : null,
  }));
}

export type PublishGameResult = {
  id: string;
  /** Raw manage token, returned ONLY for account-less authors to store client-side. */
  manageToken?: string;
};

/**
 * Insert a published game. When `authorId` is null (account-less author), a
 * manage token is minted and its hash stored in `game_tokens`; the raw token is
 * returned so the caller can hand it to the client. Registered authors own the
 * row via `author_id` and get no token.
 */
export async function publishGame(params: {
  authorId: string | null;
  game: ValidatedGame;
  columns: GameColumns;
}): Promise<PublishGameResult> {
  const { authorId, game, columns } = params;

  return db.transaction(async (tx) => {
    const [row] = await tx
      .insert(games)
      .values({
        authorId,
        title: game.title,
        description: game.description,
        moves: game.moves,
        startingFen: game.startingFen,
        playerColor: game.playerColor,
        engineConfig: game.engineConfig,
        operationLogs: game.operationLogs,
        playSettings: game.playSettings,
        result: game.result,
        engineKind: columns.engineKind,
        engineElo: columns.engineElo,
        moveCount: columns.moveCount,
        cleanRate: columns.cleanRate,
      })
      .returning({ id: games.id });

    let manageToken: string | undefined;
    if (!authorId) {
      const { token, tokenHash } = generateManageToken();
      await tx.insert(gameTokens).values({ gameId: row.id, tokenHash });
      manageToken = token;
    } else {
      // Surface the publish on the home timeline. Account-less games have no
      // actor (feed_items.actor_id is NOT NULL), so they list under
      // /games/shared but never emit a feed item.
      await tx.insert(feedItems).values({
        entityType: 'game',
        entityId: row.id,
        actorId: authorId,
        metadata: { result: game.result },
      });
    }

    return { id: row.id, manageToken };
  });
}

export type GameMutationAuth = 'ok' | 'not_found' | 'forbidden';

/**
 * Authorize an owner mutation (edit / delete) on a shared game. Ownership is
 * dual: a registered author owns via `author_id` (session `userId`), while an
 * account-less author proves ownership with the raw manage `token` (compared
 * against the stored hash in constant time). Returns 'not_found' for a missing
 * or already-deleted game, 'forbidden' when neither path matches.
 */
export async function authorizeGameMutation(params: {
  gameId: string;
  userId: string | null;
  token: string | null;
}): Promise<GameMutationAuth> {
  const { gameId, userId, token } = params;

  const [row] = await db
    .select({ authorId: games.authorId, tokenHash: gameTokens.tokenHash })
    .from(games)
    .leftJoin(gameTokens, eq(gameTokens.gameId, games.id))
    .where(and(eq(games.id, gameId), isNull(games.deletedAt)))
    .limit(1);

  if (!row) return 'not_found';
  if (userId && row.authorId === userId) return 'ok';
  if (token && row.tokenHash && manageTokenMatches(token, row.tokenHash)) return 'ok';
  return 'forbidden';
}

/** Soft-delete a shared game (owner or moderation). RLS / reads filter it out. */
export async function softDeleteSharedGame(gameId: string): Promise<void> {
  await db
    .update(games)
    .set({ deletedAt: new Date(), status: 'removed' })
    .where(eq(games.id, gameId));
}

/** Update an owner-editable field set (title / description). */
export async function updateSharedGameFields(
  gameId: string,
  fields: { title: string; description: string | null }
): Promise<void> {
  await db
    .update(games)
    .set({ title: fields.title, description: fields.description })
    .where(eq(games.id, gameId));
}

/**
 * Author id of a live game — used for the like notification. `null` for an
 * account-less (anonymous) game; `undefined` if the game is missing or deleted.
 */
export async function getGameLikeOwner(gameId: string): Promise<string | null | undefined> {
  const [row] = await db
    .select({ authorId: games.authorId, deletedAt: games.deletedAt })
    .from(games)
    .where(eq(games.id, gameId))
    .limit(1);
  if (!row || row.deletedAt !== null) return undefined;
  return row.authorId;
}
