/**
 * Shared-game writes.
 *
 * @description
 * Writes a published game (and, for account-less authors, its manage token) in
 * one transaction, plus the owner mutations (soft delete, field edits). Reads
 * live in `./games-read`, mutation authorization in `./games-auth`. The game
 * `id` is a UUIDv7 generated by the schema's `$defaultFn`; `status` defaults
 * to `'public'`.
 *
 * @see {@link @/lib/games/publish-game} for the validation + column derivation
 *      that produces the inputs here.
 */
import { and, eq, isNull } from 'drizzle-orm';
import 'server-only';

import { generateManageToken } from '@/lib/games/manage-token';
import type { GameColumns, ValidatedGame } from '@/lib/games/publish-game';
import { clawbackPointsForPost } from '@/lib/points';
import { createAdminClient } from '@/lib/supabase/admin';

import { db } from './index';
import { feedItems, gameTokens, games } from './schema';

export type PublishGameResult = {
  id: string;
  /** Raw manage token, returned ONLY for account-less authors to store client-side. */
  manageToken?: string;
};

/**
 * Insert a published game. When `authorId` is null (account-less author), a
 * manage token is minted and its hash stored in `game_tokens`; the raw token is
 * returned so the caller can hand it to the client. Registered authors own the
 * row via `author_id` and get no token.
 */
export async function publishGame(params: {
  authorId: string | null;
  game: ValidatedGame;
  columns: GameColumns;
}): Promise<PublishGameResult> {
  const { authorId, game, columns } = params;

  return db.transaction(async (tx) => {
    const [row] = await tx
      .insert(games)
      .values({
        authorId,
        title: game.title,
        description: game.description,
        moves: game.moves,
        startingFen: game.startingFen,
        setupPlies: game.setupPlies,
        playerColor: game.playerColor,
        engineConfig: game.engineConfig,
        operationLogs: game.operationLogs,
        operationTotals: game.operationTotals,
        undoneLogs: game.undoneLogs,
        playSettings: game.playSettings,
        playSettingsLog: game.playSettingsLog,
        maiaChargeId: game.maiaChargeId,
        result: game.result,
        engineKind: columns.engineKind,
        engineElo: columns.engineElo,
        moveCount: columns.moveCount,
        cleanRate: columns.cleanRate,
      })
      .returning({ id: games.id });

    let manageToken: string | undefined;
    if (!authorId) {
      const { token, tokenHash } = generateManageToken();
      await tx.insert(gameTokens).values({ gameId: row.id, tokenHash });
      manageToken = token;
    } else {
      // Surface the publish on the home timeline. Account-less games have no
      // actor (feed_items.actor_id is NOT NULL), so they list under
      // /games/shared but never emit a feed item.
      await tx.insert(feedItems).values({
        entityType: 'game',
        entityId: row.id,
        actorId: authorId,
        metadata: { result: game.result },
      });
    }

    return { id: row.id, manageToken };
  });
}

const GAME_GIFS_BUCKET = 'game-gifs';

/**
 * Best-effort removal of any cached replay GIFs for a deleted game
 * (`gifs/${gameId}/*.gif` — see `generateGameGif`). Failures are swallowed:
 * an orphaned GIF just wastes a little Storage space, which isn't worth
 * blocking or failing the deletion over. Deliberately no cron sweep to catch
 * what this misses either (unlike the post-images reaper): soft-deleting a
 * published game is rare and GIF storage is cheap, so a scheduled job would
 * cost more to own than the bytes it reclaims.
 */
async function cleanupGameGifs(gameId: string): Promise<void> {
  try {
    const admin = createAdminClient();
    const prefix = `gifs/${gameId}`;
    const { data: files } = await admin.storage.from(GAME_GIFS_BUCKET).list(prefix);
    if (!files || files.length === 0) return;
    await admin.storage.from(GAME_GIFS_BUCKET).remove(files.map((f) => `${prefix}/${f.name}`));
  } catch (error) {
    console.warn('softDeleteSharedGame: failed to clean up cached GIFs', gameId, error);
  }
}

/**
 * Soft-delete a shared game (owner or moderation). Stamps `deleted_at` only —
 * `status` (the visibility tier) is intentionally left untouched so the two
 * lifecycle axes stay orthogonal. RLS / reads filter on `deleted_at IS NULL`.
 */
export async function softDeleteSharedGame(gameId: string): Promise<void> {
  await db.transaction(async (tx) => {
    const [row] = await tx
      .update(games)
      .set({ deletedAt: new Date() })
      .where(eq(games.id, gameId))
      .returning({ authorId: games.authorId });

    // Reverse the publish reward on removal. `author_id` is null for an
    // account-less game (or a missing row) — clawbackPointsForPost no-ops on a
    // null user — and only a registered author's publish ever earned a grant.
    // Idempotent (`post_clawback:game:<id>`), so a re-delete is a safe no-op.
    if (row) await clawbackPointsForPost(tx, row.authorId, { type: 'game', id: gameId });
  });

  await cleanupGameGifs(gameId);
}

/** Update an owner-editable field set (title / description). */
export async function updateSharedGameFields(
  gameId: string,
  fields: { title: string; description: string | null }
): Promise<void> {
  await db
    .update(games)
    .set({ title: fields.title, description: fields.description })
    .where(eq(games.id, gameId));
}

/**
 * Claim an account-less published game for a registered user: set
 * `author_id` and burn the manage token, per the `game_tokens` design
 * (PK=FK, token deleted on claim).
 *
 * The UPDATE is guarded by `author_id IS NULL`, so a double or concurrent
 * claim loses atomically at the row level — no read-check-write window.
 * Returns false when nothing was claimed (already claimed, deleted, or
 * gone); the caller maps that to its own error code.
 *
 * Token verification is NOT done here — the caller must have already
 * authorized via `authorizeGameMutation` with the manage token.
 */
export async function claimSharedGame(gameId: string, userId: string): Promise<boolean> {
  return db.transaction(async (tx) => {
    const claimed = await tx
      .update(games)
      .set({ authorId: userId })
      .where(and(eq(games.id, gameId), isNull(games.authorId), isNull(games.deletedAt)))
      .returning({ id: games.id });

    if (claimed.length === 0) return false;

    await tx.delete(gameTokens).where(eq(gameTokens.gameId, gameId));
    return true;
  });
}
